### ISSUE TITLE
Cannot acquire synchronized frames consistently

### ISSUE THREAD

**Issue by Suedocode** [orbbec/OrbbecSDK-dev#5]
The goal right now is trying to acquire DEPTH and COLOR frames that have matching timestamps from a single camera. Here is the code being used:

```
#include <libobsensor/ObSensor.hpp>
#include <libobsensor/hpp/Utils.hpp>
#include <mutex>
#include <condition_variable>
#include <sstream>

static constexpr uint32_t s_fps = 15;

static constexpr uint32_t s_dw = 640;
static constexpr uint32_t s_dh = 576;
static constexpr uint32_t s_dsz = s_dw*s_dh*2;

static constexpr uint32_t s_cw = 1920;
static constexpr uint32_t s_ch = 1080;
static constexpr uint32_t s_csz = s_dw*s_dh*4;

using namespace std::chrono;

int main() {
  ob::Context::setLoggerSeverity(OB_LOG_SEVERITY_WARN);
  ob::Context ctx;
  auto mDev = ctx.queryDeviceList()->getDevice(0);
  auto mPipeline = std::make_shared<ob::Pipeline>(mDev);
  auto mConfig = std::make_shared<ob::Config>();

  mConfig->enableStream(
      mPipeline
        ->getStreamProfileList(OB_SENSOR_DEPTH)
        ->getVideoStreamProfile(s_dw, s_dh, OB_FORMAT_Y16, s_fps)
      );
  mConfig->enableStream(
      mPipeline
        ->getStreamProfileList(OB_SENSOR_COLOR)
        ->getVideoStreamProfile(s_cw, s_ch, OB_FORMAT_BGRA, s_fps)
      );
  mConfig->setAlignMode(ALIGN_DISABLE);
  mPipeline->enableFrameSync();

  std::cout << "Starting pipeline" << std::endl;
  std::condition_variable cv;
  std::mutex mut;
  std::shared_ptr<ob::FrameSet> frameset;
  mPipeline->start(
      mConfig,
      [&](std::shared_ptr<ob::FrameSet> fs) {
        std::unique_lock lk(mut);
        frameset = std::move(fs);
        cv.notify_one();
      });

  auto start_time = system_clock::now();
  while(true) {
    std::stringstream ss;
    struct print_ss_t {
      std::stringstream& ss;
      ~print_ss_t() { std::cout << ss.str() << std::endl; }
    };
    print_ss_t sps{ss};

    std::unique_lock lk(mut);
    frameset = nullptr;
    cv.wait(lk, [&](){ return frameset != nullptr; });

    auto df = frameset->depthFrame();
    auto cf = frameset->colorFrame();
    if (df) ss << "DEPTH{" << df->getTimeStampUs()/1000 << "} ";
    if (cf) ss << "COLOR{" << cf->getTimeStampUs()/1000 << "} ";

    if (!frameset || !df || !cf) continue;
    auto now = system_clock::now();
    ss << "COMPLETE frameset in " << duration_cast<milliseconds>(now - start_time).count() << "ms";
    start_time = now;
  }
}
```

Here is the output
```
[09/27 15:23:30.917896][warning][5925][AlgParamManager.cpp:319] Get imu calibration param failed!load default param.
[09/27 15:23:31.221683][warning][5925][FemtoMegaDevice.cpp:115] Execute failure! A std::exception has occurred!
 - where: FemtoMegaDevice.cpp(115):operator()
 - msg: Could not load library "./extensions/frameprocessor/libob_frame_processor.so"
./extensions/frameprocessor/libob_frame_processor.so: cannot open shared object file: No such file or directory
 - type: N5dylib10load_errorE
[09/27 15:23:31.221804][warning][5925][DeviceBase.cpp:219] Execute failure! A std::exception has occurred!
 - where: DeviceBase.cpp(219):getComponent
 - msg: DeviceComponentPtr is nullptr
 - type: St13runtime_error
[09/27 15:23:31.544669][warning][5925][ObException.cpp:5] Component 7 not found!
[09/27 15:23:31.544785][warning][5925][DeviceBase.cpp:219] Execute failure! A libobsensor_exception has occurred!
 - where: DeviceBase.cpp(219):getComponent
 - msg: Component 7 not found!
 - type: N11libobsensor23invalid_value_exceptionE
Starting pipeline
DEPTH{5242} 
COLOR{9437} 
COLOR{9961} 
COLOR{10485} 
DEPTH{10485} 
DEPTH{11010} COLOR{11010} COMPLETE frameset in 924ms
COLOR{11534} 
COLOR{12058} 
COLOR{12582} 
COLOR{13172} 
COLOR{13697} 
COLOR{14221} 
COLOR{14745} 
COLOR{15335} 
DEPTH{14088165181036167} 
COLOR{15859} 
COLOR{16384} 
COLOR{196} 
DEPTH{12095692971538710} 
DEPTH{13238} 
COLOR{720} 
DEPTH{13762} 
COLOR{1310} 
DEPTH{14286} 
COLOR{1835} 
DEPTH{13229077606221152} 
...
```

1. Is this libob_frame_process.so error an issue? It doesn't appear in the ldd list for libOrbbecSDK.so. I see it compiled in the OrbbecSDK-dev build directory, but none of the examples show it in their ldd lists either. It looks like it's dlopened with a raw local path. I see this error when running the examples as well within the OrbbecSDK-dev build directory unless i run it specifically from build/linux_x86_64/bin.

2. Complete framesets arrive irregularly at first, and then not at all. How can I enforce complete framesets with matching timestamps always?

3. Incoming frames are incredibly inconsistent (likely associated with problem 2). At 15FPS, I expect ~66ms between each frame timestamp. These outputs show delays of hundreds or even thousands of milliseconds between each frame category, long depth pauses, and absurd (or corrupted) timestamps.

All three of these symptoms are probably related, but I wanted to point them out individually.

I created a symbolic link of build/linux_x86_64/bin/extensions into the directory of my test in order to fix the libob_frame_process.so error, and it seems to resolve the dlopen error but doesn't change the output behavior issues.

I do see /usr/lib/extensions/frameprocessor/libob_frame_processor.so installed, but it looks like the dlopen only uses relative paths.

**Environment:**
Ubuntu 22.04.5 LTS (x86_64)
g++ 11.4.0
OrbbecSDK 7e05e5805d7181f401ffa5e870352b096b573eb1
Firmware v1.2.9

**Comment by Sirudoi** [comment]
1. The `libob_frame_process.so` is an extension library for OrbbecSDK. As you mentioned, it is loaded via `dlopen` and defaults to a relative path `. /extensions`. We provide the `ob::Context::setExtensionsDirectory()` interface, which allows you to customize the path for loading extension libraries. For example, you can set the extension directory path to `/home/user/lib/extensions` using `ob::Context::setExtensionsDirectory("/home/user/lib/extensions")`. Please note that this interface must be called before any other OrbbecSDK interfaces. We will also provide documentation in the future to explain how to set the extension reading directory.

2. The issue you mentioned in point 2 is related to point 3. This was caused by an internal SDK code issue, which has now been resolved. You can pull the latest code from the develop branch for verification. Regarding your question on how to enforce obtaining complete framesets, you can achieve this by setting the mode to `OB_FRAME_AGGREGATE_OUTPUT_ALL_TYPE_FRAME_REQUIRE` using `ob::Config::setFrameAggregateOutputMode()`,  after you have called `enableFrameSync()`.

Thank you for bringing these issues to our attention. We truly appreciate your patience and support. If you encounter any further problems, please feel free to let us know!

**Comment by Sirudoi** [comment]
1. The `libob_frame_process.so` is an extension library for OrbbecSDK. As you mentioned, it is loaded via `dlopen` and defaults to a relative path `./extensions`. We provide the `ob::Context::setExtensionsDirectory()` interface, which allows you to customize the path for loading extension libraries. For example, you can set the extension directory path to `/home/user/lib/extensions` using `ob::Context::setExtensionsDirectory("/home/user/lib/extensions")`. Please note that this interface must be called before any other OrbbecSDK interfaces. We will also provide documentation in the future to explain how to set the extension reading directory.

2. The issue you mentioned in point 2 is related to point 3. This was caused by an internal SDK code issue, which has now been resolved. You can pull the latest code from the develop branch for verification. Regarding your question on how to enforce obtaining complete framesets, you can achieve this by setting the mode to `OB_FRAME_AGGREGATE_OUTPUT_ALL_TYPE_FRAME_REQUIRE` using `ob::Config::setFrameAggregateOutputMode()`, after you have called `enableFrameSync()`.

Thank you for bringing these issues to our attention. We truly appreciate your patience and support. If you encounter any further problems, please feel free to let us know!

**Comment by Suedocode** [comment]
Updated to bd2d4dd41d6214c9d8bfe3365efa865d5fe8df9f and now I get the correct outputs:
```
Starting pipeline
DEPTH{246913141} COLOR{246913140} COMPLETE frameset in 715ms
DEPTH{246913207} COLOR{246913207} COMPLETE frameset in 56ms
DEPTH{246913274} COLOR{246913274} COMPLETE frameset in 68ms
DEPTH{246913341} COLOR{246913340} COMPLETE frameset in 86ms
DEPTH{246913408} COLOR{246913407} COMPLETE frameset in 53ms
DEPTH{246913474} COLOR{246913474} COMPLETE frameset in 73ms
DEPTH{246913541} COLOR{246913541} COMPLETE frameset in 50ms
...
```

The added config option makes things more simple too.
